INSERT INTO `items` (`id`,`category`,`item_name`,`description`,`price`) VALUES (1,'tea','All Nighter','Tart',10);
INSERT INTO `items` (`id`,`category`,`item_name`,`description`,`price`) VALUES (2,'tea','Bahama Mama','Tropical',10);
INSERT INTO `items` (`id`,`category`,`item_name`,`description`,`price`) VALUES (3,'tea','Beach Please','Tropical',10);
INSERT INTO `items` (`id`,`category`,`item_name`,`description`,`price`) VALUES (4,'tea','Blue Hawaiian','Tropical',10);
INSERT INTO `items` (`id`,`category`,`item_name`,`description`,`price`) VALUES (5,'tea','Captain America','Berry',10);
INSERT INTO `items` (`id`,`category`,`item_name`,`description`,`price`) VALUES (6,'tea','Cucumber Watermelon','Watermelon',10);
INSERT INTO `items` (`id`,`category`,`item_name`,`description`,`price`) VALUES (7,'tea','Fuzzy Navel','Peach',10);
INSERT INTO `items` (`id`,`category`,`item_name`,`description`,`price`) VALUES (8,'tea','Georgia Peach','Peach',10);
INSERT INTO `items` (`id`,`category`,`item_name`,`description`,`price`) VALUES (9,'tea','Gummi Bear','Watermelon',10);
INSERT INTO `items` (`id`,`category`,`item_name`,`description`,`price`) VALUES (10,'tea','Happy Camper','Berry',10);
INSERT INTO `items` (`id`,`category`,`item_name`,`description`,`price`) VALUES (11,'tea','Jolly Rancher','Berry',10);
INSERT INTO `items` (`id`,`category`,`item_name`,`description`,`price`) VALUES (12,'tea','Lake Days','Berry',10);
INSERT INTO `items` (`id`,`category`,`item_name`,`description`,`price`) VALUES (13,'tea','Margarita','Tropical',10);
INSERT INTO `items` (`id`,`category`,`item_name`,`description`,`price`) VALUES (14,'tea','Miami Vice','Tropical',10);
INSERT INTO `items` (`id`,`category`,`item_name`,`description`,`price`) VALUES (15,'tea','Mermaid','Tart',10);
INSERT INTO `items` (`id`,`category`,`item_name`,`description`,`price`) VALUES (16,'tea','Spring Breaker','Tropical',10);
INSERT INTO `items` (`id`,`category`,`item_name`,`description`,`price`) VALUES (17,'tea','Sweetart','Tart',10);
INSERT INTO `items` (`id`,`category`,`item_name`,`description`,`price`) VALUES (18,'tea','Tiger Tea','Tropical',10);
INSERT INTO `items` (`id`,`category`,`item_name`,`description`,`price`) VALUES (19,'tea','Unicorn','Tart',10);
INSERT INTO `items` (`id`,`category`,`item_name`,`description`,`price`) VALUES (20,'tea','Watermelon Crawl','Watermelon',10);
INSERT INTO `items` (`id`,`category`,`item_name`,`description`,`price`) VALUES (21,'tea','Wave Runner','Tropical',10);
INSERT INTO `items` (`id`,`category`,`item_name`,`description`,`price`) VALUES (22,'shake','Banana Pudding','Dessert',10);
INSERT INTO `items` (`id`,`category`,`item_name`,`description`,`price`) VALUES (23,'shake','Cheesecake','Dessert',10);
INSERT INTO `items` (`id`,`category`,`item_name`,`description`,`price`) VALUES (24,'shake','Chocolate Caramel Cheesecake','Chocolate',10);
INSERT INTO `items` (`id`,`category`,`item_name`,`description`,`price`) VALUES (25,'shake','Chocolate Chip Cookie Dough','Chocolate',10);
INSERT INTO `items` (`id`,`category`,`item_name`,`description`,`price`) VALUES (26,'shake','Cinnamon Roll','Dessert',10);
INSERT INTO `items` (`id`,`category`,`item_name`,`description`,`price`) VALUES (27,'shake','Cookies n\' Cream','Chocolate',10);
INSERT INTO `items` (`id`,`category`,`item_name`,`description`,`price`) VALUES (28,'shake','Chocolate Elvis','Chocolate',10);
INSERT INTO `items` (`id`,`category`,`item_name`,`description`,`price`) VALUES (29,'shake','Funfetti','Dessert',10);
INSERT INTO `items` (`id`,`category`,`item_name`,`description`,`price`) VALUES (30,'shake','Peanut Butter Cup','Candy',10);
INSERT INTO `items` (`id`,`category`,`item_name`,`description`,`price`) VALUES (31,'shake','Salted Caramel','Dessert',10);
INSERT INTO `items` (`id`,`category`,`item_name`,`description`,`price`) VALUES (32,'shake','Snickers','Candy',10);
INSERT INTO `items` (`id`,`category`,`item_name`,`description`,`price`) VALUES (33,'shake','Tiramisu','Dessert',10);
INSERT INTO `items` (`id`,`category`,`item_name`,`description`,`price`) VALUES (34,'shake','White Chocolate Snickers','Candy',10);
INSERT INTO `items` (`id`,`category`,`item_name`,`description`,`price`) VALUES (35,'shake','Wildberry','Fruit',10);
INSERT INTO `items` (`id`,`category`,`item_name`,`description`,`price`) VALUES (36,'beauty','Garden of Eden','Vitamins and Energy',10);
INSERT INTO `items` (`id`,`category`,`item_name`,`description`,`price`) VALUES (37,'beauty','Queen Bee','Vitamins and Energy',10);
INSERT INTO `items` (`id`,`category`,`item_name`,`description`,`price`) VALUES (38,'beauty','Aloha','Vitamins and Energy',10);
INSERT INTO `items` (`id`,`category`,`item_name`,`description`,`price`) VALUES (39,'beauty','Spa Day','Vitamins and Energy',10);
INSERT INTO `items` (`id`,`category`,`item_name`,`description`,`price`) VALUES (40,'specialty','Kitchen','Best of Everything',10);
INSERT INTO `items` (`id`,`category`,`item_name`,`description`,`price`) VALUES (41,'specialty','Pretty n Pink','Best of Everything',10);
INSERT INTO `items` (`id`,`category`,`item_name`,`description`,`price`) VALUES (42,'specialty','GodFather','Best of Everything',10);
INSERT INTO `items` (`id`,`category`,`item_name`,`description`,`price`) VALUES (43,'specialty','Hercules','Best of Everything',10);
INSERT INTO `items` (`id`,`category`,`item_name`,`description`,`price`) VALUES (44,'donut','Donut Hole Shot','Fat Burner',10);
